title: BAPL Support
description: BAPL Support
theme: just-the-docs
color_scheme: beck

url: https://ba-pl.github.io/wiki/
baseurl: /assets/images
enable_copy_code_button: true
logo: "https://github.com/BA-PL/wiki/blob/main/assets/images/logo4.png?raw=true"
aux_links:
  "Infosys":
    - "https://infosys.beckhoff.com/index_en.htm"
aux_links_new_tab: true
url: https://infosys.beckhoff.com/index_en.htm

aux_links:
  Infosys: https://infosys.beckhoff.com/index_en.htm

permalink: pretty

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
